# Generated by Django 6.0.7 on 2026-07-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_dailyfatiguereport_dailysleepreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="rest_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="sets_reps",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="TrainingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.exercise",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.training",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="training",
            name="exercises",
        ),
        migrations.AddField(
            model_name="training",
            name="exercises",
            field=models.ManyToManyField(
                through="authentication.TrainingExercise", to="authentication.exercise"
            ),
        ),
    ]
