# Generated by Django 6.0.7 on 2026-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_exercise_rest_time_exercise_sets_reps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
