# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_training_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="remedy",
            name="reminder_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
