# Generated by Django 6.0.7

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_remedy_reminder_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remedy",
            name="days_of_week",
        ),
        migrations.AddField(
            model_name="remedy",
            name="days_of_week",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Monday", "Segunda-feira"),
                        ("Tuesday", "Terça-feira"),
                        ("Wednesday", "Quarta-feira"),
                        ("Thursday", "Quinta-feira"),
                        ("Friday", "Sexta-feira"),
                        ("Saturday", "Sábado"),
                        ("Sunday", "Domingo"),
                    ],
                    max_length=9,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
