# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_remedy_days_of_week_array"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remedy",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
