# Generated by Django 6.0.7 on 2026-07-12 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_remedy_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemedyIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "remedy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to="authentication.remedy",
                    ),
                ),
            ],
            options={
                "unique_together": {("remedy", "date")},
            },
        ),
    ]
