# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_remedyintake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remedy",
            name="quantity",
            field=models.CharField(default="1", max_length=50),
        ),
    ]
